/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "systick.h"
#include "alarm.h"

int main(void)
{
    // Initialize apps
    Init_Alarm();

    StartSysTick();

    while (1) {
        // Run apps
        Task_Alarm();

        WaitForSysTick();
    }
}
